### PR TITLE
[ui] rewrote progress bar

### PR DESCRIPTION
**Pull request by mbarzda**
* rewrote ProgressBar function to es6 class;
* updated vitals progress bars placement;
* added progress bars scaling for other than 1080p resolutions;
* rewrote progressbar ticking to use `setTimeout` instead `setInterval`.

## before
[](https://ibb.co/D7Kk7dC)
[](https://ibb.co/LQ1r5vX)

## after
[](https://ibb.co/Nscy0FW)
[](https://ibb.co/CvhDrwd)

### CODE REVIEW

**Comment by tabarra** [comment]
That looks great.  
On a second note, why is the default font Time News Roman?

**Comment by ImagicTheCat** [comment]
Issues:
* many arbitrary syntax changes compared to the code base
  * class syntax
  * why `setTimeout` over `setInterval` ?
  * why `> -1` instead of `>= 0` ? 
  * template literals

Unfortunately, whatever how much you prefer this syntax, when you contribute to a project it's better to follow the already existing syntax (however `let` is probably better than `var` in most cases; I don't like JS).

I don't know if the actual behavior changes about the position/scaling of the progress bar is working for all resolutions of the game, but a pull request only about that could be interesting.

**Comment by ENDrain** [comment]
> Issues:
> 
> * many arbitrary syntax changes compared to the code base
>   
>   * class syntax
>   * why `setTimeout` over `setInterval` ?
>   * why `> -1` instead of `>= 0` ?
>   * template literals
> 
> Unfortunately, whatever how much you prefer this syntax, when you contribute to a project it's better to follow the already existing syntax (however `let` is probably better than `var` in most cases; I don't like JS).

Since you have such admitably high standards concerning contributions to your project, may I respectfully suggest introducing contribution guidlines, with possible inclusion of preferred code style.

**Review by ENDrain — APPROVED** [review]
Good job on refactoring `vrp/cfg/ProgressBar.js`. Code is better structured and readable.

**Comment by ImagicTheCat** [comment]
Hm... I want to remove all JS code from the project, probably with a straightforward transpiler, thus JS guidelines will not help.

**Pull request closed without merging**
