### PR TITLE
Update base.lua

### PR DESCRIPTION
**Pull request by NunoNovais**
new function and tunnel getHeading
Usefull to work in combination with get Position

### CODE REVIEW

**Comment by ImagicTheCat** [comment]
Eventually the heading parameter could be added to multiple features, but I don't know if I will work on that, so this can be a start.
Issues:
- commit name (too vague)
- no doc (code and documentation files)

**Comment by NunoNovais** [comment]
The reason why, comes from the need of if for a vRP2 addon i am working, i will need to position and heading the player before playing animations, i could get the heading other ways, but it seems better to implement in the vRP core as we already have position

**Comment by ENDrain** [comment]
Vague commit naming shouldn't be an issue because you can set your own commit message when merging, one that describes the changes. Since the changes have received your approval, I can't see how could this be so hard to document them with your own hand since they are so tiny. And may I again recommend introducing contribution guidlines, clear and thorough, to prevent any future delays of such kind in approving pull requests.

**Review by Boss-Man-Dev — COMMENTED** [review]
Fixed to accept entity parameter for any future development with this function.

**Pull request merged**
